{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 > 5", "trace": "self = <test_demo.TestClass object at 0x105bff550>\n\n    def test_two(self):\n        print(\"执行2条测试用例\")\n        x = 1\n>       assert x > 5\nE       assert 1 > 5\n\ntest_demo.py:14: AssertionError"}, "attachments": [{"name": "stdout", "source": "b686660d-d783-4948-be3c-1dcea1ef6e32-attachment.txt", "type": "text/plain"}], "start": 1639141208583, "stop": 1639141208583, "uuid": "f85b4d3b-9291-4180-b236-d849d0bfaab1", "historyId": "2d0d16e2408f4d2f8493afef51e7aae4", "testCaseId": "e5bed4573f4b2e21facc4335ba66a7ba", "fullName": "test_demo.TestClass#test_two", "labels": [{"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "liuqideMacBook-Pro.local"}, {"name": "thread", "value": "32632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo"}]}